import type { Metadata } from "next";
import "./globals.css";

// fonts importation
import { KumbhSans } from "@/lib/fonts";

// components importation
import Wrapper from "@/components/Wrapper/Wrapper";
import Header from "@/components/Header/Header";

// global context importation
import ContextComponent from "@/context/Context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`${KumbhSans.className}`}>
        <ContextComponent>
          <Wrapper>
            <Header />
            {children}
          </Wrapper>
        </ContextComponent>
      </body>
    </html>
  );
};

export default RootLayout;
